name: CI
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout Repo'
      - name: 'Install NPM'
        run: npm install
      - name: 'Run Test'
        run: npm run test

